### ISSUE TITLE
custom.ini instructions do not work

### ISSUE THREAD

**Issue by paulgibbs** [Chassis/phpini#12]
Per the readme, the custom.ini instructions do not work. /phpinfo.php reports the default PHP memory_limit (128mb).

**Comment by paulgibbs** [comment]
`/etc/php/7.0/fpm/conf.d/custom.ini` exists but it's the same contents as original template, not the wp-content/custom.ini override: https://github.com/Chassis/phpini/blob/master/modules/phpini/templates/custom.ini.erb

**Comment by roborourke** [comment]
@BronsonQuick just seen the issue, hardcoded paths for the content directory here: https://github.com/Chassis/phpini/blob/master/modules/phpini/manifests/init.pp#L35

Should be using the mapped paths variable.
